# -*- coding: utf-8 -*-
"""Desafio1_Sistema Simples de gerenciamneto de registro de alunos.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hhAcTQEjfy24Vw7djD1oHgUAA5XqcVyp
"""

nome_Aluno = input("Digite o nome do Aluno:  ")

id_Aluno = int(input("Digite o Id do Aluno:  "))

nota_Aluno = input("Digite a notas do Aluno:  ")
nota_Aluno = [float(nota) for nota in nota_Aluno.split()]

print("Nome do Estudante: ", nome_Aluno)
print("ID do Estudante:  ", id_Aluno)
print("Notas do Estudante: ", nota_Aluno)

nomes_Alunos = []
ids_Alunos = []
notas_Alunos = []

num_Alunos = int(input("Digite a Quantidades de Alunos a serem Cadastrados: "))

for i in range(num_Alunos):
  print(f"Informações do Aluno {i+1}: ")
  nome = input("Digite o nome do Aluno: ")
  id_aluno = input("Digite o ID do Aluno: ")
  notas = input("Digite as notas separadas por espaço: ")

  nomes_Alunos.append(nome)
  ids_Alunos.append(id_aluno)
  notas_Alunos.append(notas)

for i in range(num_Alunos):
  print(f"\n Informações do Aluno {i+1}: ")
  print("Nome do Estudante: ", nomes_Alunos[i])
  print("Id do Estudante: ", ids_Alunos[i])
  print("Notas do Aluno: ", notas_Alunos[i])